version: '3.3'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: facul
    ports:
      - "5432:5432"
      ##Pasta Padrão para armazenamento e persistência de Dados##
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    networks:
      - redeteste

  #Criação de um contâiner para iniciar login com o pgadmin4:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "email123@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - redeteste

  app:
    image: tema13
    container_name: tema13
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - redeteste

    restart: always
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgress
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/facul

networks:
  redeteste:
    driver: bridge